# Introduction {#intro}

**This is the syllabus for BIOSCI 1540: Computational Biology.**

This is both the first course in the core sequence of classes of the Computational Biology major and also an elective for most Biological Sciences majors.

This syllabus contains both key course policies and also is a repository for useful information about computational biology.

The first several pages contain key information about the course.  Subsequent pages are organized alphabetically by major topic.

Pages marked "Appendix" are additional information about computational biology or research that you may find useful.

Your first assignment in the class will be to read through the syllabus and complete a "Syllabus treasure hunt" assignment on Canvas.  

If you have a question about the syllabus (after you complete the syllabus treasure hunt) or even just spot a typo, post a comment on [GitHub](https://github.com/brouwern/BIOSCI_1540) at [https://github.com/brouwern/BIOSCI_1540](https://github.com/brouwern/BIOSCI_1540)  

You'll be shown how to add comments on GitHub in class.  The next page of the syllabus is a page for practicing adding comments.
