# Assessments Overview {#assessments}

The primary form of assessment in the course will be regular tests **(5).**
<!-- Annual update: current number of tests? -->

Other forms of assessment will include,  
1. **Test revisions** (aka Test Reworks), which will count as a form of homework and do not add points back to your test.  
1. **Canvas Quiz questions** related to lecture videos, **Code checkpoints** to assure that you can execute key functions, and **Software checkpoints** to assure that you have the proper software involved.
1. Additional homework
1. Practice tests or test preparation assignments.

## Test-taking policies

Tests will be in-person during the regularly schedule time and administered as a combination of 

1. Stand-alone canvas quiz questions
1. Canvas quiz questions based on code I provide
1. Code-based questions which you'll answer via a separtate file, submitted via Canvas.


## Key test policies

1. All answers will be submitted by the end of the normal class period.  
1. If you are unable to take or complete an exam your score will be eligible to be dropped or replaced as specified elsewhere in the syllabus.
1. It is your responsibility to assure that you have adequate power in your devices and internet access to complete exams.  
1. Adjustments will be made as necessary for students with DRS accommodations.
1. You may not communicate with other students while taking a test.

## Test dropping policy

Your lowest unit test will be dropped.  Your second-lowest score can be replaced by the final, if you score higher on the final.  See the section on the final exam for further explanation.

<!-- TODO: students in quarantine? -->


<!-- Prior to any test policies for each test will be clearly articulated during lecture and in writing. -->

<!-- TODO: Tests will be open book and open note.   -->
<!--  -->


## Final Exam Policies

The final will cover conceptual material covered after the Unit 4 test.  You will also need to draw on R skills from throughout the semester. 

The final exam will ...
1, Take place during finals week on the day scheduled by the University
1. Is required
1. Follow the general format of other tests.


The final exam is required and will be scheduled as per the University calendar. 

As noted elsewhere your lowest test score will be automatically dropped and your score for tests calculated based on your 3 best tests.  Additionally,  I will compare your performance on the final to those three tests and if your score on the final is higher then I will upgrade that score to your score on the final.  Your final eaxm can therefore contribute to you score in 2 ways - as the final, and as a replacement of your second lowest of the 4 unit tests.  Therefore, one of your exams is always dropped, and a second one is potentially replaced.


## Exam "buffer question" policy

The unit tests and the final exam will have 1 to 2 "buffer points."  The way this work is that there will be, for example, 26 questions but the test will be worth a maximum of 25 points.  The maximum score on the test will be capped at 25 points.  If you miss 1 question you will get 25/25 points instead of 25/26.  If you miss two questions you will get 24/25 and so forth.  Scores greater than 100% will not be given.