






# Assessment methods & Grading policies

```{marginfigure, echo = TRUE}
**Students will be assesed the following ways**: 
1. 3 midterm exams  
2. 1 final test which combines 2 exams: 
a) Exam on materials for the final week(s) of class   
b)Cumulative exam integrating all course material  
3. Regular homework assignments  
4. Lecture participation & in-class work (eg. via TopHat)  

```


## General exam policies

1. See the course schedule for dates
1. The lowest of your 3 regular midterm grades (each worth 15% of final grade) can be replaced by the cumulative portion of the final exam (also worth 15%) if your final grade is higher.
1. If you miss 1 test for any reason it will be counted zero and replaced by your score on the cumlative final.  If you miss a 2nd test it will recieve a score of 0.
1. Your score on the unit 4 exam taken during the final cannot be replaced by your final exam score.
1. No make up tests will be given
1. No extra credit will be offered on tests

## Exam review policies

1. I will make every effort to have exams graded within 2 weeks
1. You will be permitted to look over the paper exam and ask questions during recitation. Exams DO NOT leave the room.  Scantrons will not be returned.
1. I will (generally) cover the most missed questions during the recitation exam review.  
1. I will not review individual exams during office hours.  I will answer general concept questions.
1. You may not reproduce any part of the exam in any way while looking at your exam.  No photos, copying of questions, etc.
1. Any student caught removing an exam or answer key, or reproducing any part of an exam or answer key, will be given a 0 on the exam and charged with an Academic Integrity violation.
1. If you would like to challenge an exam question, there will be an opportunity to do so.  Otherwise, points are not awarded back unless a grading error occurred.  If a grading error occurred, please see me.

## Final exam policies


1. If you have 3 final exams scheduled for the same day, you must speak to me one month BEFORE final exams.
1. Students missing the **final exam** due to a documented EMERGENCY should contact me ASAP. Oversleeping, travel plans, family vacations, incorrect date, and minor illness are not emergencies.


## Homework grade policies


```{marginfigure, echo = TRUE}
Your lowest 2 homework scores will be dropped
```


1. No late assignmetns will be accepted.  Once an assignment closes where it has been posted it will no longer be accepted.
1. There will be no make up homework assignments given.  
1. If you miss an assignment it will recieve a 0.  Your 1st 2 missed assignments will be dropped.  Any additional missed assignments will recieve a 0.



## Point allocation


## Grade scale




# Required Course Materials

## Textbook



Zotero?



## Books for computational biology




**Coglan, A.  n.d.  A little book of R for bioinformatics.**
Adapated as an R package: xxxxxx
https://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/ 

Focal Chapters in Coglan (n.d.):
Chapter 1: Introduction
CHapter 2: Access to information
Chapter 3: Pairwise alignment
Chapter 4: BLAST
Chapter 5: Advanced BLAST
Chapter 6: Multiple sequence alignment
Chapter 7: Molecular Phylogeny and Evolution
Chapter 12: Proteomics
Chapter 13: Protein structure







```{marginfigure, echo = TRUE}
Mueller, PA & DM Oppenheimer.  2014.  The pen is mightier than the keyboard: Advantages of longhand over laptop note taking.  Psych Sci.  
Cepeda et al.  2014.  Laptop multitasking hinders classroom learning for both users & nearby peers.  Comp & Ed.
```

It is your responsibility to use your devices responsibly.  There is extensive evidence that hand writing notes is far more effective for learning than typing notes (Mueller & Oppenheimer 2014, Cepeda et al 2014).  If you device use is disruptive to the class you will recieve a warning.  A 2nd violation will result in the loss of TopHat points for the class.  If a 3rd violation occurs no longer permitted to use a device in class and you will recieve a zero for all remaining in-class TopHat points since you will no longer be able to use a device in-class.

## Computers in class

If possible I’d like everyone to bring a laptop on the first day of class loaded with the software for the class.  If access to a laptop is in any way a problem, let me know so we can chat.  Also, if you have any problems loading the software listed below let me know.


# Types of assignments

## Tests

### Midterm exam

There will be XXX midterm exams.

### Final exam

There will be a full length final exam held at the schedule time.  If you have scheduling conflicts please contact the registrar.

## Class participation

### In-class worksheets 

Occassionaly you will be asked to complete a short worksheet or draw an example of a diagram in-class related to a lecture or discussion. These will be collected and graded for participation similar to TopHat participation questions.

### TopHat participation questions

I will regularly use TopHat to ask short questions (eg, multiple choice) to assess your understanding or survey the class.  To account for malfunctioning devices etc you will recieve full credit if you answer at least 75% of the question for a session.  Additionally, you will be able to drop you two lowest TopHat participation scores, for example if you are absent.

### Forced participation questions

During lectures and discussions I will randomly select students to answer my question or engage in a conversation with me.  Selection will be random, without replacement, until everyone has participated, then will begin again. If you are not present I will skip you.  If you are present we will engage in a discussion, and you are free to say "I don't know" to any question I ask.  I will then follow up. You will not be graded on the quality of your response, but rather on your participation and willingness to engage in discussion.  I assume everyone will get full credit on this.

## Software check points (SCPs)

We will use several types of software during this class and it is imperative that you have downloaded, installed, and checked the software prior to classes or the beginning of assignments.  To make sure this happens you will generally be required to submit a selfie of yourself in front of your computer with the software open.  These files will be submitted, with the correct file name, to a designated shared folder.


## In-class assignments

Worksheets, TopHat assignments
Begun in class, due latter.===

## Out-of class assignments

### Reading assignments and quizes

### Online tutorial completion

Tyically worksheets

## Mini-projects

Sub-components of mini-projects will be assigned and graded as in-class assignments or out-of-class assignments.

## Team project


Sub-components of mini-projects will be assigned and graded as in-class assignments or out-of-class assignments.























## Appendix: 

## Appendix: Regular expressions

The RStudio cheatsheet for regular expressions can be found here
https://github.com/rstudio/cheatsheets/raw/master/regex.pdf


## Data structures in R

www.datasciencecentral.com/profiles/blogs/understand-basic-to-advance-data-structure-used-in-r-to-use-it

## Appendix: Twitter accounts to follow

@justsaysinmice,
@justsaysinrats,
@justsaysrisks,
@OnlyInMen

