# Academic integrity

Dr. Brouwer, the Bio Sci department, and the University all take academic integrity very seriously. Cheating includes any form of plagiarism, including copying other students' work or using other resources without proper attribution.

1. If you are caught cheating on a graded assignment, you will receive a zero on the assignment. 
1. If you are caught cheating on an exam, you will receive a zero on the exam, an F in the course, and an Academic Integrity Violation Report will be filed. 


<!-- Materials made available to you in this class are my intellectual property. They are for your private use only. Posting or sharing my materials (lecture notes, slides, quizzes, homework, exams, recitation assignments, etc) to any website or with any student not currently enrolled in this course, without my express written permission, is a violation of the academic integrity code.  I have accounts on these sites and monitor them. -->


Below is the University's Policy on Academic Integrity:

> "Students in this course are expected to comply with the University of Pittsburgh School of Arts & Sciences Academic Integrity Code located at www.as.pitt.edu/faculty/policy/integrity.html. Any student suspected of failing to meet the student obligations of the code during the semester will be required to participate in the procedures for adjudication, initiated at the instructor level. This may include, but is not limited to, confiscation of the assignment of any individual suspected of violating the code. A minimum sanction of a zero score for the assignment will be imposed. Violation of the Academic Integrity Code requires the instructor to submit an Academic Integrity Violation Report to the Dean."
