# Course materials - Software

Installation and account creation for all software will be covered in detail during class or via assignments and accompanying videos.  If you want to get prepared early for the course you can explore these on your own.

For information on getting started with R see [Get R Done!](https://brouwern.github.io/getRdone/).

## Primary software

### Programming environment: R

We will use the open-source language [R](https://cran.r-project.org/) for almost everything in this course.

**NOTE**: If you have used R before that's awesome!    

However, **PLEAE PLEASE PLEASE update your installation when the class begins** - R goes through regular updates and works best with the newest version.

If you are having trouble installing R an excellent resource is: 
https://learningstatisticswithr.com/book/introR.html


**REFERENCE**  
R Core Team (2021). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. www.R-project.org/.



### Integrated developement environment (IDE)

We'll use [RStudio](https://www.rstudio.com/) as the front-end for working with R.

**NOTE**: If you've use RStudio before **please update it** when the course begins.

**[RStudio](https://www.rstudio.com/:** www.rstudio.com/products/rstudio/download/#download  

### Cloud-based R

We will use several web-based services to run R.  First, we will use the online machine-learning platform [Kaggle](https://www.kaggle.com/) and the Notebooks feature to run code in a user-friendly environment.  You can make a Kaggle account with your University or personal email address.

Additionally, as a back-up to running R on your desktop I'll also introduce you to [RStudio Cloud](https://rstudio.cloud/.  There are also several excellent [primers](https://rstudio.cloud/learn/primers) which we'll use.  

**[RStudio cloud](https://rstudio.cloud/):** https://rstudio.cloud/ 

<!-- ## Code sharing -->

<!-- ### Microsoft SharePoint -->

<!-- R code and other files will be distributed to you via a personal folder on **SharePoint**, accessed via your **OneDrive** account. -->

<!-- You will need to "sync" your OneDrive account to your computer desktop to allow me to help you with your work.  No code files will be shared via email or Canvas during the course. -->


<!-- **NOTE**: If you do not have access to a computer you can sync your OneDrive account please contact me so we can workout a system. -->


<!-- TODO: how to sync onedrive -->

<!-- ### GitHub -->

<!-- Most code for this course will be available on [GitHub](https://github.com/ ) and you will need to create an account for some activities.   -->

<!-- Links will be distributed directly to you, but you can also see key resources pinned to my profile at [https://github.com/brouwern](https://github.com/brouwern) -->



## R packages

Many R **packages** (aka libraries) will be used in this course.  Below are several key ones.

### swirl {#swirl}

*swirl* is an R package that sets up interactive tutorials in your R console.  It works both on desktop computers and RStudio cloud and is an excellent tool for learning and reviewing R.  

Details for installing swirl can be found here in [Get R Done!](https://brouwern.github.io/getRdone/swirl.html#swirl).

### Bioconductor

**Bioconductor** is a clearing house and repository for high-grade bioinformatics and computational biology software using R. 

Details for installing Bioconductor can be found [here](https://brouwern.github.io/lbrb/installing-bioconductor.html).