# Bibliography

Below are resources that you may wish to use for reference during the course or in the future for review.

## Bioinformatics & computational biology

**Pevsner 2015.  Bioinformatics and functional genomics. 3rd edition.**    
Available **FREE** via the Pitt library, though you can only download a few chapters at a time.  I do **NOT** recommend buying a hard copy because I am currently only planning on using the first 1/3 of the book.  If you want a hard copy and buy it used be sure to get the 3rd edition.

## Phylogenetics

**Wiley, EO and BS Liberman.  2011.  Phylogenetics: Theory and Practice of Phylogenetic Systematics.  2nd ed.**  
Available **FREE** via the Pitt library, though you can only download a few chapters at a time.  I do **NOT** recommend buying a hard copy because I am currently only planning on using a few chapters.  If you want a hard copy and buy it used be sure to get the 2nd edition.

Focal chapters in Wiley and Liberman (2011):
* Chapter 4: Tree graphs
* Chapter 5: Characters & homology
* Chapter 6: Parsimony & parsimony analysis
* Chapter 7: Parametric phylogenetics

## Statistics

**Navarro, D. 2019.  Learning Statistics with R**
PDF: https://learningstatisticswithr.com/lsr-0.6.pdf  
HTML: https://learningstatisticswithr.com/book/   

Focal chapters in Navarro:
* ["Getting started with R"](https://learningstatisticswithr.com/book/introR.html)
* ["Additional R concepts"](https://learningstatisticswithr.com/book/mechanics.html)
* ["Descriptive statistics"](https://learningstatisticswithr.com/book/descriptives.html)
* ["Pragmatic matters"](https://learningstatisticswithr.com/book/datahandling.html)
* ["Drawing graphs"](https://learningstatisticswithr.com/book/graphics.html#hist)
* ["Basic programming"](https://learningstatisticswithr.com/book/scripting.html)
* ["Introduction to probability"](https://learningstatisticswithr.com/book/probability.html)

## Reference Books

Cadotte & Davies.  Phylogenies in ecology: A guide to concepts and methods.
Free from library.  Covers the use of phylogenies in community ecology and trait evolution. 

Nei and Kumar.  Molecular evolution and phylogenetics.
Free from library. Contains more mathematical treatments of maximum likelihood etc.


## Reference articles, blogs etc

Altman.  2009.  [Bioinformatics & computational biology = Same?  No.](https://rbaltman.wordpress.com/2009/02/18/bioinformatics-computational-biology-same-no/) ttps://rbaltman.wordpress.com  

Gregory 2008.  Understanding evolutionary trees.  Evo Edu Outreach 1:121-137.

Koonin.  2001.  Computational genomics.  Current Biology 11:R155-R158.

Loman and Watson.  2013.  So you want to be a computational biologist?  Nature Biotech.

Markowetz, F.  2017.  All biology is computational biology.  PLoS Biology.

Nascimente, FF et al.  2017.  A biologist's guide to Bayesian phylogenetic analysis.  Nature Ecology & Evolution.  See GitHub repo and blog posts.

Nussinov et al.  2015.  From "What is?" to "What isn't?" computational biology.  PLoS Computational Biology.

Visser et al 2015.  Speeding up ecological and evolutionary computations in R: Essential of high performanc computing for biologists.  PLoS Computational Biology.
