# Metnal health & wellness

School is hard - please take care of yourself as best you can given the many demands on your time. Diminished mental health, including significant stress, mood changes, excessive anxiety, or problems with sleeping can interfere with your academic performance. You have a support network here at Pitt to help you through challenging times. Acknowledging that you need help, and getting that help, is smart and courageous.

* If you are in an EMERGENCY situation, call 911 or Pitt Police at 412-624-2121.
* If your symptoms are due to FINANCIAL strain, please visit pitt.libguides.com/assistanceresources to see all available University resources.
* If your symptoms are due to strained RELATIONSHIPS, families, or personal crises, please visit the University Counseling Center at www.studentaffairs.pitt.edu/cc/ for free confidential services.
* If your symptoms are strictly related to your COURSE WORK and performance in this course, please contact me.

## Resources: 

**University Counseling Center**:  412-648-7930  
**Sexual Assault Response**:  412-648-7856  
**RE:SOLVE crisis network**: 888-796-8226  
**Pitt Police**:  412-624-2121  
[**Pitt Pantry food bank**](https://www.studentaffairs.pitt.edu/pittserves/the-pitt-pantry/): https://www.studentaffairs.pitt.edu/pittserves/the-pitt-pantry/
